server:
  port: 8080

spring:
  h2:
    console.enabled: true
    console.path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true

query:
  internal-query: '{
    findAllInvestments {
      investmentId 
      fundId 
      fundName
      email
      closeDate
      classType
      clientAccountNumber
      clientAccountName
      bankName 
      bankAba
      accountNum
      accountName
      swiftCode
      ffc
      bankReference
      taxId
      amount
      managementFee
      ir
      compliance
      investorName
      investorId
      investorDob
      addressLine1
      addressLine2
      city
      state
      zip
    }
  }'
  internal-by-id-query: '{  
   findInvestmentById(id: %o) {
      investmentId 
      fundId 
      fundName
      email
      closeDate
      classType
      clientAccountNumber
      clientAccountName
      bankName 
      bankAba
      accountNum
      accountName
      swiftCode
      ffc
      bankReference
      taxId
      amount
      managementFee
      ir
      compliance
      investorName
      investorId
      investorDob
      addressLine1
      addressLine2
      city
      state
      zip
    }
  }'
  sales-query: '{
    findAllInvestments {
      investmentId 
      fundId 
      email
      closeDate
      clientAccountNumber
      clientAccountName
    }
  }'
  sales-by-id-query: '{  
    findInvestmentById(id: %o) {
      investmentId 
      fundId 
      email
      closeDate
      clientAccountNumber
      clientAccountName
    }
  }'
  purchase-query: '{
    findAllInvestments {
      investmentId 
      bankName 
      bankAba
      accountNum
      accountName
      swiftCode
      ffc
    }
  }'
  purchase-by-id-query: '{  
    findInvestmentById(id: %o) {
      investmentId 
      fundId 
      email
      closeDate
      clientAccountNumber
      clientAccountName
    }
  }'
